# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 16:21
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_ID', models.CharField(max_length=10)),
                ('Course_Name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_Name', models.CharField(max_length=45)),
                ('Email_Address', models.CharField(max_length=45)),
                ('Position', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Incident_ID', models.CharField(max_length=10)),
                ('Incident_Type', models.CharField(max_length=45)),
                ('Location', models.CharField(max_length=45)),
                ('Kind_of_Students', models.CharField(max_length=45)),
                ('Group_or_Individual', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Issue_Name', models.CharField(max_length=45)),
                ('Issue_Type', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Request_Type', models.CharField(max_length=45)),
                ('Time_Appointment', models.DateTimeField(auto_now_add=True)),
                ('Time_Submitted_Appointment', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=45)),
                ('Email_Address', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Advisor_Counselor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Counselor_Name', models.CharField(max_length=45)),
                ('Email_Address', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ed4all.Faculty')),
                ('Incident_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ed4all.Incident')),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ed4all.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Issue_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ed4all.Issue')),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ed4all.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GPA', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('Current_Semester', models.CharField(max_length=45)),
                ('Program', models.CharField(max_length=45)),
                ('School', models.CharField(max_length=45)),
                ('Student_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ed4all.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='Counselor_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ed4all.Student_Advisor_Counselor'),
        ),
        migrations.AddField(
            model_name='request',
            name='Counselor_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ed4all.Student_Advisor_Counselor'),
        ),
        migrations.AddField(
            model_name='request',
            name='Student_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ed4all.Student'),
        ),
    ]
