# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-22 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.CharField(db_column='Faculty_ID', max_length=8, primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(db_column='Faculty_Name', max_length=45)),
                ('email_address', models.CharField(blank=True, db_column='Email_Address', max_length=45, null=True)),
                ('position', models.CharField(blank=True, db_column='Position', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Faculty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.CharField(db_column='Issue_ID', max_length=8, primary_key=True, serialize=False)),
                ('issue_name', models.CharField(db_column='Issue_Name', max_length=45)),
                ('issue_type', models.CharField(db_column='Issue_Type', max_length=45)),
            ],
            options={
                'db_table': 'Issue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.CharField(db_column='Request_ID', max_length=8, primary_key=True, serialize=False)),
                ('request_type', models.CharField(db_column='Request_Type', max_length=45)),
                ('time_of_appointment', models.DateTimeField(db_column='Time_of_Appointment')),
                ('time_of_submitted_appointment', models.DateTimeField(db_column='Time_of_Submitted_Appointment')),
                ('student_id', models.IntegerField(db_column='Student_ID')),
                ('counselor_id', models.IntegerField(db_column='Counselor_ID')),
            ],
            options={
                'db_table': 'Request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(db_column='Student_ID', max_length=8, primary_key=True, serialize=False)),
                ('student_name', models.CharField(db_column='Student_Name', max_length=45)),
                ('email_address', models.CharField(blank=True, db_column='Email_Address', max_length=45, null=True)),
                ('counselor_id', models.CharField(blank=True, db_column='Counselor_ID', max_length=8, null=True)),
            ],
            options={
                'db_table': 'Student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentAdvisorCounselor',
            fields=[
                ('counselor_id', models.CharField(db_column='Counselor_ID', max_length=8, primary_key=True, serialize=False)),
                ('counselor_name', models.CharField(db_column='Counselor_Name', max_length=45)),
                ('email_address', models.CharField(blank=True, db_column='Email_Address', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Student_Advisor_Counselor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_column='Student_ID', max_length=8)),
                ('incident_id', models.IntegerField(db_column='Incident_ID')),
                ('faculty_id', models.IntegerField(db_column='Faculty_ID')),
            ],
            options={
                'db_table': 'Student_Incident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_column='Student_ID', max_length=8)),
                ('issue_id', models.CharField(db_column='Issue_ID', max_length=4)),
            ],
            options={
                'db_table': 'Student_Issue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('student_id', models.CharField(db_column='Student_ID', max_length=8, primary_key=True, serialize=False)),
                ('gpa', models.DecimalField(blank=True, db_column='GPA', decimal_places=2, max_digits=3, null=True)),
                ('credits_completed', models.CharField(blank=True, db_column='Credits_Completed', max_length=8, null=True)),
                ('current_semester', models.CharField(db_column='Current_Semester', max_length=45)),
                ('program', models.CharField(db_column='Program', max_length=45)),
                ('school', models.CharField(db_column='School', max_length=45)),
                ('track_representitve', models.CharField(blank=True, db_column='Track_Representitve', max_length=30, null=True)),
                ('international_or_not', models.CharField(blank=True, db_column='International_or_not', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Student_Profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('Incident_ID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Incident_Type', models.CharField(max_length=45)),
                ('Location', models.CharField(max_length=45)),
                ('Kind_of_Students', models.CharField(max_length=45)),
                ('Group_or_Individual', models.CharField(max_length=20)),
            ],
        ),
    ]
