# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed4all', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='Student_ID',
            field=models.CharField(default='0', max_length=8, primary_key=True, serialize=False),
        ),
    ]
