# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-29 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed4all', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='incident',
            table='Incident',
        ),
    ]
