# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-29 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ed4all', '0003_auto_20170429_1800'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='counselor',
            table='Counselor',
        ),
        migrations.AlterModelTable(
            name='educator',
            table='Educator',
        ),
        migrations.AlterModelTable(
            name='studentprofile',
            table='StudentProfile',
        ),
    ]
