# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed4all', '0004_auto_20170408_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Ranking',
            field=models.CharField(default='', max_length=2),
        ),
    ]
