# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed4all', '0005_course_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='Credits_Completed',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='student_profile',
            name='Track_Representative',
            field=models.CharField(default='', max_length=30),
        ),
    ]
