# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-16 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ed4all', '0006_auto_20170408_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('review', models.TextField()),
            ],
            options={
                'db_table': 'Review',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='request',
            name='Counselor_ID',
        ),
        migrations.RemoveField(
            model_name='request',
            name='Student_ID',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Counselor_ID',
        ),
        migrations.RemoveField(
            model_name='student_incident',
            name='Faculty_ID',
        ),
        migrations.RemoveField(
            model_name='student_incident',
            name='Incident_ID',
        ),
        migrations.RemoveField(
            model_name='student_incident',
            name='Student_ID',
        ),
        migrations.RemoveField(
            model_name='student_issue',
            name='Issue_ID',
        ),
        migrations.RemoveField(
            model_name='student_issue',
            name='Student_ID',
        ),
        migrations.RemoveField(
            model_name='student_profile',
            name='Student_ID',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Student_Advisor_Counselor',
        ),
        migrations.DeleteModel(
            name='Student_Incident',
        ),
        migrations.DeleteModel(
            name='Student_Issue',
        ),
        migrations.DeleteModel(
            name='Student_Profile',
        ),
    ]
